use_frameworks!

target 'BusinessGather_Example' do
  pod 'BusinessGather', :path => '../'

  target 'BusinessGather_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
    
    
  pod 'AutoModel'
  pod 'NFAFile'
  pod 'SwiftProjects'
  pod 'ProThirdpart'
  pod 'NFAToolkit' 
    
  end
end
